# Generated by Django 5.0 on 2023-12-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Educationlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Educationqualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_qualification', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Educationspecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_specialization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employeedirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Eventdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencelevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_level', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Jobrequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobposition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maritalstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(choices=[('choice1', 'Choice 1'), ('choice2', 'Choice 2')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reasonforchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_change', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Screeningmode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_mode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sourcetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Candidatedirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_alert', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact_no_primary', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('contact_no_alternate', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('referred_by_other', models.CharField(blank=True, max_length=250, null=True)),
                ('address_line', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('education_specialization_other', models.TextField(blank=True, null=True)),
                ('education_institution_other', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('current_employer', models.CharField(blank=True, max_length=100, null=True)),
                ('current_designation', models.TextField(blank=True, null=True)),
                ('current_monthly_salary', models.IntegerField(blank=True, null=True)),
                ('expected_monthly_salary', models.IntegerField(blank=True, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_path', models.TextField(blank=True, null=True)),
                ('resume_path', models.TextField(blank=True, null=True)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('geo_location', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('city', models.ForeignKey(blank=True, db_column='city', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cand_app.city')),
                ('education_level', models.ForeignKey(blank=True, db_column='education_level', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cand_app.educationlevel')),
                ('education_qualification', models.ForeignKey(blank=True, db_column='education_qualification', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cand_app.educationqualification')),
                ('education_specialization', models.ForeignKey(blank=True, db_column='education_specialization', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cand_app.educationspecialization')),
                ('referred_by', models.ForeignKey(blank=True, db_column='referred_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cand_app.employeedirectory')),
                ('event', models.ForeignKey(blank=True, db_column='event', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cand_app.eventdetails')),
                ('experience_level', models.ForeignKey(blank=True, db_column='experience_level', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cand_app.experiencelevel')),
                ('gender', models.ForeignKey(blank=True, db_column='gender', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cand_app.gender')),
                ('job_position', models.ForeignKey(blank=True, db_column='job_position', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cand_app.jobrequisition')),
                ('marital_status', models.ForeignKey(blank=True, db_column='marital_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cand_app.maritalstatus')),
                ('persona', models.ForeignKey(blank=True, db_column='persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cand_app.persona')),
                ('reason_for_change', models.ForeignKey(blank=True, db_column='reason_for_change', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cand_app.reasonforchange')),
                ('screening_mode', models.ForeignKey(blank=True, db_column='screening_mode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cand_app.screeningmode')),
                ('education_institution', models.ForeignKey(blank=True, db_column='education_institution', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cand_app.source')),
                ('source', models.ForeignKey(blank=True, db_column='source', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_for_candidate_details', to='cand_app.source')),
                ('source_type', models.ForeignKey(blank=True, db_column='source_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cand_app.sourcetype')),
            ],
        ),
    ]
